# Classification (2)
## Iris data

In [5]:
# sklearn.datasets module always brings data looking like dictionary.
from sklearn import datasets

In [7]:
# Get dataset
iris = datasets.load_iris()
type(iris), iris                            # type: Bunch object

(sklearn.utils.Bunch,
 {'data': array([[5.1, 3.5, 1.4, 0.2],
         [4.9, 3. , 1.4, 0.2],
         [4.7, 3.2, 1.3, 0.2],
         [4.6, 3.1, 1.5, 0.2],
         [5. , 3.6, 1.4, 0.2],
         [5.4, 3.9, 1.7, 0.4],
         [4.6, 3.4, 1.4, 0.3],
         [5. , 3.4, 1.5, 0.2],
         [4.4, 2.9, 1.4, 0.2],
         [4.9, 3.1, 1.5, 0.1],
         [5.4, 3.7, 1.5, 0.2],
         [4.8, 3.4, 1.6, 0.2],
         [4.8, 3. , 1.4, 0.1],
         [4.3, 3. , 1.1, 0.1],
         [5.8, 4. , 1.2, 0.2],
         [5.7, 4.4, 1.5, 0.4],
         [5.4, 3.9, 1.3, 0.4],
         [5.1, 3.5, 1.4, 0.3],
         [5.7, 3.8, 1.7, 0.3],
         [5.1, 3.8, 1.5, 0.3],
         [5.4, 3.4, 1.7, 0.2],
         [5.1, 3.7, 1.5, 0.4],
         [4.6, 3.6, 1. , 0.2],
         [5.1, 3.3, 1.7, 0.5],
         [4.8, 3.4, 1.9, 0.2],
         [5. , 3. , 1.6, 0.2],
         [5. , 3.4, 1.6, 0.4],
         [5.2, 3.5, 1.5, 0.2],
         [5.2, 3.4, 1.4, 0.2],
         [4.7, 3.2, 1.6, 0.2],
         [4.8, 3.1, 1.6, 0.2],
         

In [9]:
# Set x and y
x = iris.data
y = iris.target
x.shape, y.shape

((150, 4), (150,))

In [11]:
# Confirm category of y data
import numpy as np
np.unique(y)

array([0, 1, 2])

In [14]:
# Split train & test data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.85, random_state=5)
x_train.shape, x_test.shape

((127, 4), (23, 4))

In [19]:
# Regression object
from sklearn.linear_model import LogisticRegression
logi = LogisticRegression(solver='newton-cg')           # Changed solver as the code below cast warning

In [20]:
# Fit model with data
logi.fit(x_train, y_train)
logi.classes_, logi.coef_, logi.intercept_

(array([0, 1, 2]),
 array([[-0.43399638,  0.8941057 , -2.35467719, -1.02093544],
        [ 0.68432277, -0.5119369 , -0.16568917, -1.05106566],
        [-0.25032639, -0.3821688 ,  2.52036636,  2.07200109]]),
 array([  9.41459576,   1.74974005, -11.16433581]))

In [24]:
# Predict y_test data
# Softmax fx is used for multimonial classes
import pandas as pd
pd.DataFrame(logi.predict_proba(x_test), columns=['Cat_0', 'Cat_1', 'Cat_2']).head()

Cat_0     Cat_1         Cat_2
0  0.027951  0.949961  2.208835e-02
1  0.000108  0.242999  7.568931e-01
2  0.000097  0.038322  9.615807e-01
3  0.987919  0.012081  4.525860e-08
4  0.000001  0.006586  9.934129e-01

In [27]:
# Compare with the actual y_test data
pd.DataFrame(y_test, columns=['Category']).head()

Category
0         1
1         2
2         2
3         0
4         2

In [28]:
# Confirm with score value - mean accuracy
logi.score(x_test, y_test) 

0.9130434782608695

In [30]:
logi.decision_function(x_test)

array([[-1.09686139,  2.42911595, -1.33225455],
       [-5.52360918,  2.19372174,  3.32988744],
       [-5.05818598,  0.91781646,  4.14036951],
       [ 7.10088251,  2.69695312, -9.79783563],
       [-7.40726707,  1.19552309,  6.21174399],
       [ 0.64249704,  2.27643315, -2.91893019],
       [ 6.46959547,  3.12493297, -9.59452843],
       [-3.42497891,  1.46182012,  1.96315879],
       [ 5.95526039,  3.16022741, -9.1154878 ],
       [-2.37411808,  1.58707257,  0.78704551],
       [-2.46091735,  1.72393712,  0.73698023],
       [-4.35634227,  2.20593694,  2.15040533],
       [-7.02102124,  1.88781704,  5.1332042 ],
       [-7.83282133,  2.32491932,  5.50790202],
       [ 6.10871558,  2.74523952, -8.8539551 ],
       [ 5.63834411,  2.74319   , -8.38153412],
       [-4.28109803,  1.97494877,  2.30614927],
       [-7.59678965,  2.37257655,  5.2242131 ],
       [ 6.56901538,  2.67665964, -9.24567502],
       [ 6.61508865,  3.16160726, -9.7766959 ],
       [-1.475211  ,  2.4615436 , -0.986